# Generated by Django 3.1.7 on 2022-02-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(default='')),
                ('name', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('en_name', models.TextField(default='')),
                ('serviced_area_file', models.FileField(blank=True, null=True, upload_to='services_areas')),
                ('prices_file', models.FileField(blank=True, null=True, upload_to='prices')),
                ('mail', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionOfActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(default='')),
                ('qualification_category', models.TextField(blank=True, default='', null=True)),
                ('work_experience', models.IntegerField(default=-1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('has_appointment', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('direction_of_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.directionofactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='GovermentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='gov_services_files')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('absolute_path', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('letter', models.FileField(blank=True, null=True, upload_to='letters')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisence', models.FileField(upload_to='lisences')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('site', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('doctors', models.ManyToManyField(blank=True, null=True, to='main.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('is_top', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('services', models.ManyToManyField(blank=True, null=True, to='main.Service')),
                ('services_types', models.ManyToManyField(blank=True, null=True, to='main.ServiceType')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('date', models.DateField(default='')),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, related_name='educations', to='main.Education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.ManyToManyField(blank=True, null=True, related_name='qualification_documents', to='main.QualificationDocument'),
        ),
        migrations.CreateModel(
            name='DirectorBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='phones',
            field=models.ManyToManyField(blank=True, null=True, to='main.BranchPhone'),
        ),
    ]
