# Generated by Django 3.1 on 2021-01-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionofactivity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
