# Generated by Django 3.1.7 on 2022-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='govermentservice',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
