# Generated by Django 3.1.7 on 2022-03-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_govermentservice_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('image', models.ImageField(upload_to='news')),
                ('new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.new')),
            ],
        ),
    ]
