# Generated by Django 3.1 on 2021-01-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_directionofactivity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionofactivity',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
