# Generated by Django 3.1.7 on 2022-03-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
