# Generated by Django 3.1 on 2021-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210130_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='education',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='education',
            name='university',
        ),
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, related_name='educations', to='main.Education'),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
