# Generated by Django 4.2.1 on 2023-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220301_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='uslugi_file',
            field=models.FileField(blank=True, null=True, upload_to='uslugi'),
        ),
    ]
