# Generated by Django 3.1 on 2021-01-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210130_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.ManyToManyField(blank=True, null=True, related_name='qualification_documents', to='main.QualificationDocument'),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
