# Generated by Django 3.1 on 2021-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210130_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
