# Generated by Django 3.1 on 2021-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210131_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='BranchPhone',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
