# Generated by Django 3.1 on 2021-01-31 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210131_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(default='')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branchphone'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
