# Generated by Django 3.1 on 2021-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210131_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.AddField(
            model_name='branch',
            name='phones',
            field=models.ManyToManyField(blank=True, null=True, related_name='branch_phones', to='main.BranchPhone'),
        ),
        migrations.AlterField(
            model_name='branchphone',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
