# Generated by Django 3.1 on 2021-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210131_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phones',
            field=models.ManyToManyField(blank=True, null=True, to='main.BranchPhone'),
        ),
    ]
