# Generated by Django 3.1 on 2021-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210131_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('site', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branches'),
        ),
    ]
