# Generated by Django 3.1 on 2021-02-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='name',
        ),
    ]
