# Generated by Django 3.1 on 2021-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
