# Generated by Django 3.1.6 on 2021-02-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210205_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microdistrict',
            name='number',
        ),
    ]
