# Generated by Django 3.1.6 on 2021-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210205_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification_category',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
