# Generated by Django 3.1.6 on 2021-02-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210211_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
