# Generated by Django 3.1.6 on 2021-02-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_servicetype_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
