# Generated by Django 3.1.6 on 2021-02-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_servicetype_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
    ]
