# Generated by Django 3.1.6 on 2021-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
