# Generated by Django 3.1.6 on 2021-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_service_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='en_name',
            field=models.TextField(default=''),
        ),
    ]
