# Generated by Django 3.1.6 on 2021-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_city_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='has_appointment',
            field=models.BooleanField(default=True),
        ),
    ]
