# Generated by Django 2.2.19 on 2021-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_hospitalsite_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_free',
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, to='main.Doctor'),
        ),
    ]
