# Generated by Django 3.1.7 on 2021-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210316_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbuilding',
            name='cabinets',
        ),
        migrations.RemoveField(
            model_name='hospitalsite',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='hospitalsite',
            name='microdistricts',
        ),
        migrations.RemoveField(
            model_name='microdistrict',
            name='hospital_buildings',
        ),
        migrations.AddField(
            model_name='city',
            name='serviced_area_file',
            field=models.FileField(blank=True, null=True, upload_to='services_areas'),
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
        migrations.DeleteModel(
            name='DistrictDoctor',
        ),
        migrations.DeleteModel(
            name='HospitalBuilding',
        ),
        migrations.DeleteModel(
            name='HospitalSite',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Microdistrict',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
