# Generated by Django 3.1.7 on 2021-05-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_govermentfile_govermentservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govermentservice',
            name='files',
        ),
        migrations.AddField(
            model_name='govermentservice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gov_services_files'),
        ),
        migrations.DeleteModel(
            name='GovermentFile',
        ),
    ]
