# Generated by Django 3.1.7 on 2021-05-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_city_gos_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='gos_services',
        ),
    ]
