# Generated by Django 3.1.7 on 2022-02-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_branchphone_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchphone',
            name='mail',
        ),
        migrations.AddField(
            model_name='city',
            name='mail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='prices_file',
            field=models.FileField(blank=True, null=True, upload_to='prices'),
        ),
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
